export function buildWorkspacePageModel(controller) {
  return {
    shell: {
      state: controller.state,
      ui: controller.ui,
      library: controller.state.library,
      activeSeries: controller.activeSeries,
      selectedVideo: controller.selectedVideo,
      selectedContextType: controller.selectedContextType,
      selectedNode: controller.selectedNode,
      previewUrl: controller.previewUrl,
      previewSeekRequest: controller.previewSeekRequest,
      summary: controller.summary,
      mindmap: controller.mindmap,
      knowledgeCards: controller.knowledgeCards,
      knowledgeCardsGenerating: controller.knowledgeCardsGenerating,
      knowledgeCardsFeedback: controller.knowledgeCardsFeedback,
      notes: controller.notes,
      tools: controller.tools,
    },
    chat: {
      messages: controller.chatMessages,
      sessions: controller.chatSessions,
      activeSessionId: controller.activeChatSessionId,
      pending: controller.chatPending,
      contextUsage: controller.contextUsage,
      contextUsageLoading: controller.contextUsageLoading,
      startNewChat: controller.onStartNewChat,
      selectChatSession: controller.onSelectChatSession,
      openSeekReference: controller.onOpenSeekReference,
      clearChat: controller.onClearChat,
      submit: controller.onSubmitChat,
    },
    generation: {
      isGeneratingSummary: controller.isGeneratingSelectedVideo,
      isGeneratingMindmap: controller.isGeneratingMindmapSelectedVideo,
      knowledgeCardsLoading: controller.knowledgeCardsLoading,
      notesLoading: controller.notesLoading,
      savingNote: controller.savingNote,
      fasterWhisperModels: controller.fasterWhisperModels,
      fasterWhisperModelsLoading: controller.fasterWhisperModelsLoading,
      downloadingModelId: controller.downloadingModelId,
      modelDownloadProgress: controller.modelDownloadProgress,
      progress: controller.state.generationProgress,
      snapshot: controller.state.generationSnapshot,
      videoDownloadProgress: controller.state.videoDownloadProgress ?? null,
    },
    actions: {
      selectSeries: controller.onSelectSeries,
      enterLibraryHome: controller.onEnterLibraryHome,
      selectVideo: controller.onSelectVideo,
      selectSeriesContext: controller.onSelectSeriesContext,
      selectTool: controller.onSelectTool,
      focusNode: controller.onFocusNode,
      openCard: controller.onOpenCard,
      generateVideo: controller.onGenerateVideo,
      generateMindmap: controller.onGenerateMindmap,
      generateKnowledgeCards: controller.onGenerateKnowledgeCards,
      createNote: controller.onCreateNote,
      updateNote: controller.onUpdateNote,
      deleteNote: controller.onDeleteNote,
      toggleSettingsPanel: controller.onToggleSettingsPanel,
      closeSettingsPanel: controller.onCloseSettingsPanel,
      changeSetting: controller.onChangeSetting,
      saveApiKey: controller.onSaveApiKey,
      downloadFasterWhisperModel: controller.onDownloadFasterWhisperModel,
      cancelFasterWhisperModelDownload: controller.onCancelFasterWhisperModelDownload,
      resetSettings: controller.onResetSettings,
      clearError: controller.onClearError,
      resolveLinkedSeries: controller.onResolveLinkedSeries,
      resolvePlaygroundVideo: controller.onResolvePlaygroundVideo,
      resolveSeriesVideo: controller.onResolveSeriesVideo,
      importLocalSeries: controller.onImportLocalSeries,
      importLocalPlaygroundVideos: controller.onImportLocalPlaygroundVideos,
      importSeriesVideos: controller.onImportSeriesVideos,
      deleteSeries: controller.onDeleteSeries,
      deleteCurrentVideo: controller.onDeleteCurrentVideo,
      downloadVideo: controller.onDownloadVideo,
    },
  };
}
