import { isGenerationSnapshotActive } from "../model/workspaceState";

export function buildWorkspacePageModel(controller) {
  const generationSnapshot = controller.currentGenerationTask?.snapshot ?? null;
  const showGenerationOverlay = isGenerationSnapshotActive(generationSnapshot);
  return {
    shell: {
      state: controller.state,
      ui: controller.ui,
      library: controller.state.library,
      activeSeries: controller.activeSeries,
      selectedVideo: controller.selectedVideo,
      selectedContextType: controller.selectedContextType,
      selectedNode: controller.selectedNode,
      previewUrl: controller.previewUrl,
      previewSeekRequest: controller.previewSeekRequest,
      summary: controller.summary,
      mindmap: controller.mindmap,
      knowledgeCards: controller.knowledgeCards,
      knowledgeCardsGenerating: controller.knowledgeCardsGenerating,
      knowledgeCardsFeedback: controller.knowledgeCardsFeedback,
      notes: controller.notes,
      tools: controller.tools,
    },
    chat: {
      messages: controller.chatMessages,
      sessions: controller.chatSessions,
      activeSessionId: controller.activeChatSessionId,
      pending: controller.chatPending,
      contextUsage: controller.contextUsage,
      contextUsageLoading: controller.contextUsageLoading,
      startNewChat: controller.onStartNewChat,
      selectChatSession: controller.onSelectChatSession,
      openSeekReference: controller.onOpenSeekReference,
      clearChat: controller.onClearChat,
      submit: controller.onSubmitChat,
    },
    generation: {
      isGeneratingSummary: controller.isGeneratingSelectedVideo,
      isGeneratingSeries: controller.isGeneratingSelectedSeries,
      isGeneratingMindmap: controller.isGeneratingMindmapSelectedVideo,
      knowledgeCardsLoading: controller.knowledgeCardsLoading,
      notesLoading: controller.notesLoading,
      savingNote: controller.savingNote,
      fasterWhisperModels: controller.fasterWhisperModels,
      fasterWhisperModelsLoading: controller.fasterWhisperModelsLoading,
      ragModels: controller.ragModels,
      ragModelsLoading: controller.ragModelsLoading,
      downloadingRagModelKey: controller.downloadingRagModelKey,
      downloadingModelId: controller.downloadingModelId,
      modelDownloadStatus: controller.modelDownloadStatus,
      modelDownloadProgress: controller.modelDownloadProgress,
      progress: generationSnapshot?.progress ?? null,
      snapshot: generationSnapshot,
      showOverlay: showGenerationOverlay,
      videoDownloadProgress: controller.state.videoDownloadProgress ?? null,
    },
    actions: {
      selectSeries: controller.onSelectSeries,
      enterLibraryHome: controller.onEnterLibraryHome,
      selectVideo: controller.onSelectVideo,
      selectSeriesContext: controller.onSelectSeriesContext,
      selectTool: controller.onSelectTool,
      focusNode: controller.onFocusNode,
      generateVideo: controller.onGenerateVideo,
      generateSeries: controller.onGenerateSeries,
      cancelGeneration: controller.onCancelGeneration,
      generateMindmap: controller.onGenerateMindmap,
      generateKnowledgeCards: controller.onGenerateKnowledgeCards,
      createNote: controller.onCreateNote,
      updateNote: controller.onUpdateNote,
      deleteNote: controller.onDeleteNote,
      toggleSettingsPanel: controller.onToggleSettingsPanel,
      openSettingsPanel: controller.onOpenSettingsPanel,
      closeSettingsPanel: controller.onCloseSettingsPanel,
      changeSetting: controller.onChangeSetting,
      saveApiKey: controller.onSaveApiKey,
      testProviderConnection: controller.onTestProviderConnection,
      downloadFasterWhisperModel: controller.onDownloadFasterWhisperModel,
      cancelFasterWhisperModelDownload: controller.onCancelFasterWhisperModelDownload,
      downloadRagModel: controller.onDownloadRagModel,
      cancelRagModelDownload: controller.onCancelRagModelDownload,
      resetSettings: controller.onResetSettings,
      clearError: controller.onClearError,
      importLocalSeries: controller.onImportLocalSeries,
      importLocalPlaygroundVideos: controller.onImportLocalPlaygroundVideos,
      importSeriesVideos: controller.onImportSeriesVideos,
      deleteSeries: controller.onDeleteSeries,
      deleteCurrentVideo: controller.onDeleteCurrentVideo,
    },
  };
}
