from backend.agent_graph.prompts.actions import VIDEO_ACTION_PLANNER_SYSTEM_PROMPT
from backend.agent_graph.prompts.query import (
    SERIES_ANSWER_SYNTHESIZER_SYSTEM_PROMPT,
    SERIES_QUERY_PROCESSOR_SYSTEM_PROMPT,
    VIDEO_ANSWER_SYNTHESIZER_SYSTEM_PROMPT,
)

__all__ = [
    "SERIES_ANSWER_SYNTHESIZER_SYSTEM_PROMPT",
    "SERIES_QUERY_PROCESSOR_SYSTEM_PROMPT",
    "VIDEO_ANSWER_SYNTHESIZER_SYSTEM_PROMPT",
    "VIDEO_ACTION_PLANNER_SYSTEM_PROMPT",
]
